<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genlibrary" nsURI="http://www.et.tu-dresden.de/ifa/agtele/genlib"
    nsPrefix="genlib">
  <eClassifiers xsi:type="ecore:EClass" name="LibraryEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LibraryItem" lowerBound="1"
        eType="#//LibraryItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MetaData" lowerBound="1"
        eType="#//MetaData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Checksum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaData">
    <eOperations name="getExternalReferenceMappers" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;AbstractExternalReferenceMapper&lt;EObject, EObject>> abstractMappers = &#xD;&#xA;&#x9;&#x9;new BasicEList&lt;AbstractExternalReferenceMapper&lt;EObject, EObject>>();&#xD;&#xA;&#xD;&#xA;// recursively iterate over all children of the metadata and collect&#xD;&#xA;// all objects that are of type 'AbstractMapper'&#xD;&#xA;Iterator&lt;Object> it = EcoreUtil.getAllContents(this, true);&#xD;&#xA;while (it.hasNext()) {&#xD;&#xA;&#x9;Object object = it.next();&#xD;&#xA;&#x9;if (object instanceof AbstractExternalReferenceMapper&lt;?, ?>) {&#xD;&#xA;&#x9;&#x9;abstractMappers.add((AbstractExternalReferenceMapper&lt;EObject, EObject>) object);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return abstractMappers;"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//AbstractExternalReferenceMapper">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="getContainerMappers" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;AbstractContainerMapper&lt;EObject, EObject>> abstractMappers = &#xD;&#xA;&#x9;&#x9;new BasicEList&lt;AbstractContainerMapper&lt;EObject, EObject>>();&#xD;&#xA;&#xD;&#xA;// recursively iterate over all children of the metadata and collect&#xD;&#xA;// all objects that are of type 'AbstractMapper'&#xD;&#xA;Iterator&lt;Object> it = EcoreUtil.getAllContents(this, true);&#xD;&#xA;while (it.hasNext()) {&#xD;&#xA;&#x9;Object object = it.next();&#xD;&#xA;&#x9;if (object instanceof AbstractContainerMapper&lt;?, ?>) {&#xD;&#xA;&#x9;&#x9;abstractMappers.add((AbstractContainerMapper&lt;EObject, EObject>) object);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return abstractMappers;"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//AbstractContainerMapper">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExternalReferenceMapper" abstract="true"
      interface="true">
    <eTypeParameters name="ExternalReferenceMapperSourceType"/>
    <eTypeParameters name="ExternalReferenceMapperTargetType"/>
    <eOperations name="getReference" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        containment="true">
      <eGenericType eTypeParameter="#//AbstractExternalReferenceMapper/ExternalReferenceMapperSourceType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target">
      <eGenericType eTypeParameter="#//AbstractExternalReferenceMapper/ExternalReferenceMapperTargetType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractContainerMapper" abstract="true"
      interface="true">
    <eTypeParameters name="ContainerMapperSourceType"/>
    <eTypeParameters name="ContainerMapperTargetType"/>
    <eOperations name="getReference" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eGenericType eTypeParameter="#//AbstractContainerMapper/ContainerMapperSourceType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container">
      <eGenericType eTypeParameter="#//AbstractContainerMapper/ContainerMapperTargetType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAttributeMapper" abstract="true"
      interface="true">
    <eTypeParameters name="AttributeMapperSourceType"/>
    <eOperations name="getAttribute" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eGenericType eTypeParameter="#//AbstractAttributeMapper/AttributeMapperSourceType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
